version: '3.8'
services:
  silcsp:
    build:
      context: ./src/backend
      dockerfile: Dockerfile-php
    container_name: silcsp
    restart: always
    volumes:
      - ./src/backend:/var/www/html/
    ports:
      - "8600:80"
    networks:
      - app

  react-app:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile-react
    container_name: react-app
    restart: always
    volumes:
      - ./src/frontend:/app/
      - /app/node_modules  # Agregamos este volumen para persistir los módulos de Node.js
    ports:
      - "3500:3000"  # Cambiamos el puerto para reflejar el puerto de desarrollo de React
    networks:
      - app

networks:
  app:
    driver: bridge
